# Generated by Django 4.1 on 2023-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_article_image_article_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="subtitle",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
