# Generated by Django 4.1 on 2023-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_article_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.CharField(max_length=180, null=True),
        ),
    ]
