# Generated by Django 4.1 on 2023-03-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_article_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="github",
        ),
        migrations.RemoveField(
            model_name="article",
            name="linkedin",
        ),
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_author",
                    models.CharField(max_length=50, verbose_name="Name"),
                ),
                (
                    "comment_content",
                    models.CharField(max_length=250, verbose_name="Content"),
                ),
                ("comment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
            ],
        ),
    ]
