# Generated by Django 4.1 on 2023-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_alter_comment_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_author",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
